version: '3'
services:
  database:
    container_name: database-app-container
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=app-database
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: web-app-container
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
    volumes:
      - .:/app
      - web_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - database
volumes:
  web_data:
  database-data:
    driver: local
